#!/bin/bash

# CONFIG
CHECK_FOR=("js" "py") # Edit this line to choose checking languages. Available: ("js" "py")
FOLDER=${PWD##*/} # Equals repo root folder if executed by pre-commit hook
CLEANER="(?<=$FOLDER/).*" # Regex used to clean output by linters (strips full absolute paths to relative path (to $FOLDER))
TEMP_FILE=".log"

# Make linter checks
check () {
  for i in ${!CHECK_FOR[@]};
  do
    lang=${CHECK_FOR[$i]}
    case "$lang" in
      'js') eslint --config bonza/.eslintrc.json -f visualstudio . | grep -oP $CLEANER
        ;;
      'py') find . -type f -name "*.py" | xargs pylint --rcfile='bonza/pylintrc' --msg-template='{path}({line}): error {msg_id} : {msg} [at {obj}]'
        ;;
    esac
  done
}


# Check if script was executed manually using ./bonza/check
if [ "check" == "$1" ]; then
  echo "$(check)" > $TEMP_FILE
  python3 bonza/formatter
  exit 0
fi


# Output after commit try
if grep -q "): error " $TEMP_FILE; then
    echo "$(check)" > $TEMP_FILE
    python3 bonza/formatter
    RED='\033[0;31m'
    echo -e "${RED} Stopped Committing!"
    echo ""
    exit 1
fi 